# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jonhef/shiny-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jonhef/shiny-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jonhef/shiny-engine/CMakeFiles /Users/jonhef/shiny-engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jonhef/shiny-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shiny-engine

# Build rule for target.
shiny-engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shiny-engine
.PHONY : shiny-engine

# fast build rule for target.
shiny-engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/build
.PHONY : shiny-engine/fast

src/evaluation/evaluation.o: src/evaluation/evaluation.cpp.o
.PHONY : src/evaluation/evaluation.o

# target to build an object file
src/evaluation/evaluation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/evaluation/evaluation.cpp.o
.PHONY : src/evaluation/evaluation.cpp.o

src/evaluation/evaluation.i: src/evaluation/evaluation.cpp.i
.PHONY : src/evaluation/evaluation.i

# target to preprocess a source file
src/evaluation/evaluation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/evaluation/evaluation.cpp.i
.PHONY : src/evaluation/evaluation.cpp.i

src/evaluation/evaluation.s: src/evaluation/evaluation.cpp.s
.PHONY : src/evaluation/evaluation.s

# target to generate assembly for a file
src/evaluation/evaluation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/evaluation/evaluation.cpp.s
.PHONY : src/evaluation/evaluation.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/searching/alpha_beta.o: src/searching/alpha_beta.cpp.o
.PHONY : src/searching/alpha_beta.o

# target to build an object file
src/searching/alpha_beta.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/searching/alpha_beta.cpp.o
.PHONY : src/searching/alpha_beta.cpp.o

src/searching/alpha_beta.i: src/searching/alpha_beta.cpp.i
.PHONY : src/searching/alpha_beta.i

# target to preprocess a source file
src/searching/alpha_beta.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/searching/alpha_beta.cpp.i
.PHONY : src/searching/alpha_beta.cpp.i

src/searching/alpha_beta.s: src/searching/alpha_beta.cpp.s
.PHONY : src/searching/alpha_beta.s

# target to generate assembly for a file
src/searching/alpha_beta.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/searching/alpha_beta.cpp.s
.PHONY : src/searching/alpha_beta.cpp.s

src/utils/board.o: src/utils/board.cpp.o
.PHONY : src/utils/board.o

# target to build an object file
src/utils/board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/board.cpp.o
.PHONY : src/utils/board.cpp.o

src/utils/board.i: src/utils/board.cpp.i
.PHONY : src/utils/board.i

# target to preprocess a source file
src/utils/board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/board.cpp.i
.PHONY : src/utils/board.cpp.i

src/utils/board.s: src/utils/board.cpp.s
.PHONY : src/utils/board.s

# target to generate assembly for a file
src/utils/board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/board.cpp.s
.PHONY : src/utils/board.cpp.s

src/utils/chess_logic.o: src/utils/chess_logic.cpp.o
.PHONY : src/utils/chess_logic.o

# target to build an object file
src/utils/chess_logic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/chess_logic.cpp.o
.PHONY : src/utils/chess_logic.cpp.o

src/utils/chess_logic.i: src/utils/chess_logic.cpp.i
.PHONY : src/utils/chess_logic.i

# target to preprocess a source file
src/utils/chess_logic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/chess_logic.cpp.i
.PHONY : src/utils/chess_logic.cpp.i

src/utils/chess_logic.s: src/utils/chess_logic.cpp.s
.PHONY : src/utils/chess_logic.s

# target to generate assembly for a file
src/utils/chess_logic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/chess_logic.cpp.s
.PHONY : src/utils/chess_logic.cpp.s

src/utils/fen_utils.o: src/utils/fen_utils.cpp.o
.PHONY : src/utils/fen_utils.o

# target to build an object file
src/utils/fen_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/fen_utils.cpp.o
.PHONY : src/utils/fen_utils.cpp.o

src/utils/fen_utils.i: src/utils/fen_utils.cpp.i
.PHONY : src/utils/fen_utils.i

# target to preprocess a source file
src/utils/fen_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/fen_utils.cpp.i
.PHONY : src/utils/fen_utils.cpp.i

src/utils/fen_utils.s: src/utils/fen_utils.cpp.s
.PHONY : src/utils/fen_utils.s

# target to generate assembly for a file
src/utils/fen_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/fen_utils.cpp.s
.PHONY : src/utils/fen_utils.cpp.s

src/utils/position.o: src/utils/position.cpp.o
.PHONY : src/utils/position.o

# target to build an object file
src/utils/position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/position.cpp.o
.PHONY : src/utils/position.cpp.o

src/utils/position.i: src/utils/position.cpp.i
.PHONY : src/utils/position.i

# target to preprocess a source file
src/utils/position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/position.cpp.i
.PHONY : src/utils/position.cpp.i

src/utils/position.s: src/utils/position.cpp.s
.PHONY : src/utils/position.s

# target to generate assembly for a file
src/utils/position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/position.cpp.s
.PHONY : src/utils/position.cpp.s

src/utils/ratio.o: src/utils/ratio.cpp.o
.PHONY : src/utils/ratio.o

# target to build an object file
src/utils/ratio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/ratio.cpp.o
.PHONY : src/utils/ratio.cpp.o

src/utils/ratio.i: src/utils/ratio.cpp.i
.PHONY : src/utils/ratio.i

# target to preprocess a source file
src/utils/ratio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/ratio.cpp.i
.PHONY : src/utils/ratio.cpp.i

src/utils/ratio.s: src/utils/ratio.cpp.s
.PHONY : src/utils/ratio.s

# target to generate assembly for a file
src/utils/ratio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shiny-engine.dir/build.make CMakeFiles/shiny-engine.dir/src/utils/ratio.cpp.s
.PHONY : src/utils/ratio.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... shiny-engine"
	@echo "... src/evaluation/evaluation.o"
	@echo "... src/evaluation/evaluation.i"
	@echo "... src/evaluation/evaluation.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/searching/alpha_beta.o"
	@echo "... src/searching/alpha_beta.i"
	@echo "... src/searching/alpha_beta.s"
	@echo "... src/utils/board.o"
	@echo "... src/utils/board.i"
	@echo "... src/utils/board.s"
	@echo "... src/utils/chess_logic.o"
	@echo "... src/utils/chess_logic.i"
	@echo "... src/utils/chess_logic.s"
	@echo "... src/utils/fen_utils.o"
	@echo "... src/utils/fen_utils.i"
	@echo "... src/utils/fen_utils.s"
	@echo "... src/utils/position.o"
	@echo "... src/utils/position.i"
	@echo "... src/utils/position.s"
	@echo "... src/utils/ratio.o"
	@echo "... src/utils/ratio.i"
	@echo "... src/utils/ratio.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

